Create ldapservice account
NethServer/nethserver-dc pull request #71
Opened 2017-12-11 16:09 UTC by DavidePrincipi

NethServer/dev#5396

2017-12-11 21:05 UTC, stephdl approved these changes

2017-12-12 08:31 UTC, gsanchietti requested changes

2017-12-12 08:31 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-dc-createldapservice
> +/sbin/e-smith/config setprop sssd BindDN "ldapservice@${domain}" BindPassword $(<$tmp_secret)
Use $sssd{Realm} instead of Domain

2017-12-12 08:31 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-dc-createldapservice
> +#!/bin/bash
Call this script from createlinks

2017-12-12 08:31 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-dc-createldapservice
> +echo "$(get_dn ldapservice)
Add a comment to document what happens

2017-12-12 08:31 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-dc-createldapservice
> +/sbin/e-smith/signal-event nethserver-sssd-save
Call only in nethserver-dc-update

2017-12-12 08:31 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-dc-sync-upn
> +my $ldif = Net::LDAP::LDIF->new($tmpLdif, 'a', onerror => 'warn', 'encode' => 'canonical', 'change' => 1);
Close the file after use, before invoking ldbmodify

2017-12-12 16:33 UTC, gsanchietti approved these changes

2017-12-14 16:13 UTC, merged