Implement the event user-cleanup
NethServer/nethserver-dc pull request #94
Opened 2018-12-02 09:19 UTC by stephdl

https://github.com/NethServer/dev/issues/5624

2018-12-03 14:18 UTC, DavidePrincipi requested changes
We must define (and document) the new key/props. Let's discuss it on community!

2018-12-03 14:18 UTC, DavidePrincipi commented on root/etc/e-smith/events/actions/nethserver-dc-user-delete-cleanup
> +my $KeepUserData = $db->get_prop('KeepUserData') || 'disabled';
We are missing a record key here!

2018-12-03 15:21 UTC, gsanchietti commented
I don't like much the current approach: we have almost the same code both on nethserver-dc and nethserver-directory.
Can we implement a single action directly into nethserver-sssd? The same can then used also for remote account provider.

Also, I would remove any prop for now and implement it only when automatic removing is in place.
@filippocarletti what do you think?

2018-12-03 16:39 UTC, DavidePrincipi commented
> Can we implement a single action directly into nethserver-sssd?

Probably, yes: the data-removal code is the same on both ad and ldap provider

2018-12-04 21:09 UTC, stephdl commented
@gsanchietti @DavidePrincipi new way, please consider also https://github.com/NethServer/nethserver-sssd/pull/109

the code to delete the home (user-cleanup) and the code to link user-delete to user-cleanup is now in nethserver-sssd

2018-12-05 16:18 UTC, DavidePrincipi approved these changes

2018-12-05 16:28 UTC, merged